# Generated by Django 2.1 on 2020-08-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher_id',
            new_name='publisher',
        ),
    ]
